### ISSUE TITLE
Set linear constraints on branch flow

### ISSUE THREAD

**Issue by dirge1** [MATPOWER/matpower#145]
Hi,

I found how to set linear constraints on voltage angles, magnitudes, real injections, and reactive injections in the User’s Manual. And it is convenient to set the maximum power of branch flow in the casefile. However, I did not find how to set linear constraints on branch flow. For example, the difference in power between two branchs must be less than 10MW. Is this possible to implement in software?

Thanks a lot in advance.

Best regards,
Shi-Shun Chen

**Comment by rdzman** [comment]
This is possible, though it is more complex, since the flows are not explicit optimization variables.

For a DC OPF, it can be added as a linear constraint on voltage angles since the flows themselves are linear functions of the angles. But for the AC OPF, it ends up being a non-linear function, so you would have to provide functions to evaluate the constraint and its derivatives as described in Section 7.1.2 in the [User's Manual](https://matpower.org/docs/MATPOWER-manual-7.1.pdf). There is an example of adding a nonlinear constraint to the OPF testing code (e.g. t opf mips) near the end,
