### ISSUE TITLE
Powerflow using Distflow algorithm in matpower

### ISSUE THREAD

**Issue by akhtar3100** [MATPOWER/matpower#181]
Dear Ray,
Is there anyway to run powerflow in manpower using distflow algorithm? Also like there is option pf.enforce-q-limits to enforce reactive power limits for generators, are there any options to enforce voltage limits on nodes or current limits on branches?

Regards,
Akhtar

**Comment by rdzman** [comment]
There are several algorithms specific to distribution systems described in Section 4.3 of the [MATPOWER User's Manual](https://matpower.org/docs/MATPOWER-manual-7.1.pdf). I don't remember off the top of my head what DistFlow refers to ... it may be one of those included.

Regarding voltage and current limits, those are available via the OPF, but not in the power flow. With power flow, for each limit you enforce you need to implement a control mechanism (or rule) for how to modify the power flow inputs in order to enforce that limit ... and the order of activating the controls matters. At some point it makes more sense to just use an OPF.
