### ISSUE TITLE
deleting branch and bus

### ISSUE THREAD

**Issue by AboLregal** [MATPOWER/matpower#196]
![ad](https://github.com/MATPOWER/matpower/assets/36906638/69309228-3084-4189-84fb-ce6c712d8863)

So I am workin on using pso to minmize generators
so I used ext2int
but after that I removed generators and i get error
why?

**Comment by rdzman** [comment]
Since the `ext2int()` function removes out-of-service equipment, it temporarily restores them so they can be included again when calling `int2ext()`. If you add or remove generators from the internally numbered case, `int2ext()` does not know about that and the data will not match what is expected when it goes to restore the offline generators. So it will through an error.

I'm guessing that's what's going on in your case, without having the data I need to reproduce the error, I can't be certain.
