### ISSUE TITLE
installation or test error with linprog

### ISSUE THREAD

**Issue by PonySubway** [MATPOWER/matpower#201]
Hi, there is an error when I use test_matpower and test_most, both in version 7.1 and 8.0. My MATLAB is R2023a
runopf() works but i am not sure about other functions. 

I am trying to use power flow calculation in MOST, is it okay if I ignore the error? 
_______________________
Error using linprog
LINPROG(f,A,b,Aeq,beq,LB,UB,X0,OPTIONS) does not accept X0. Use
LINPROG(f,A,b,Aeq,beq,LB,UB,OPTIONS) instead.

Error in qps_ot (line 268)
            linprog(c, Ai, bi, Ae, be, xmin, xmax, x0, ot_opt);

Error in qps_master (line 266)
            qps_ot(H, c, A, l, u, xmin, xmax, x0, opt);

Error in t_qps_master (line 107)
        [x, f, s, out, lam] = qps_master([], c, A, l, u, xmin, [], [], opt);

Error in t_run_tests (line 61)
    feval( test_names{k}, ~verbose );

Error in test_matpower (line 173)
all_ok = t_run_tests( tests, verbose );

**Comment by rdzman** [comment]
If you plan to use `linprog()` as a solver for MOST, you can't really ignore this.

The error is due to an incompatible change made by MATLAB in their latest release of the Optimization Toolbox. It has been fixed in [this commit](https://github.com/MATPOWER/mp-opt-model/commit/478c42c9b74f8dc6dabeb5a073e4a1aa0196d7e8).

The easiest way to resolve it is probably to put the two files below in the `mp-opt-model/lib` sub-directory under your MATLAB installation, replacing the existing ones.
- [miqps_ot.m](https://raw.githubusercontent.com/MATPOWER/mp-opt-model/master/lib/miqps_ot.m)
- [qps_ot.m](https://raw.githubusercontent.com/MATPOWER/mp-opt-model/master/lib/qps_ot.m)
