### ISSUE TITLE
Pre-Release Test Error in R2023b on Apple Silicon and Windows

### ISSUE THREAD

**Issue by sergio-dorado** [MATPOWER/matpower#209]
Hi. Now that MATLAB runs natively on Apple Silicon, I decided to try it with MATPOWER. While setting up the pre-release, I ran into the following test error (on R2023b). I did the same experiment with a Windows computer (Intel processor) on R2023b and got the same error.

Do you have any ideas of what might be causing this (other than `linprog` not accepting the given `x0` argument)?

<img width="616" alt="image" src="https://github.com/MATPOWER/matpower/assets/52328859/fde1cb2a-9387-4849-ac54-a14d53dc9b14">

**Comment by rdzman** [comment]
Yes, this is a known issue due to an incompatible change made by MATLAB to `linprog()` in R2023a. It was fixed in the master branch of MP-Opt-Model, but I have not done a full MP-Opt-Model or MATPOWER release since the fix. I know. Both are long overdue.

The easiest fix is to grab the latest [MP-Opt-Model](https://github.com/MATPOWER/mp-opt-model/) from GitHub and use it to replace the `mp-opt-model` subdirectory in your MATPOWER installation. That should fix the problem.

- [Download ZIP file](https://github.com/MATPOWER/mp-opt-model/archive/refs/heads/master.zip) of latest MP-Opt-Model

FWIW, I’m running everything on the Apple Silicon native MATLAB R2023b without issues … except some of the solvers aren’t available yet (e.g. Gurobi, Knitro, and I haven’t yet gotten a working IPOPT MEX file).
