### ISSUE TITLE
t_most_30b_3_1_17.m file is not working.

### ISSUE THREAD

**Issue by young-hwanlee** [MATPOWER/matpower#217]
I have used matpower7.1 version and tried to run "t_most_30b_3_1_17.m," but here's what I have got :

Error using mpoption
Error using mpoption
mpoption: 'sopf' is not a valid option name

Error in t_most_30b_3_1_17 (line 32)
mpopt = mpoption(mpopt, 'sopf.force_Pc_eq_P0', 0);  %% don't constrain contracted == base case dispatch

**Comment by rdzman** [comment]
This is expected behavior.

MOST includes some tests that are only run if you have access to `c3sopf`, a predecessor to MOST that solved single-period, secure, stochastic OPF. It was never released publicly, but some of the tests in `test_most` compare MOST and `c3sopf` output, if available. The `t_most_30b_3_1_17` is one of those tests which are not expected to work (and are skipped) if the package containing `c3sopf` is not available.
