### ISSUE TITLE
Add option for proportional Qg scaling in pfsoln

### ISSUE THREAD

**Issue by rwl** [MATPOWER/matpower#61]
The logic in `pfsoln` for scaling `Qg` in proportion with `Qmax` and `Qmin` is quite complicated. Perhaps it could be made optional, with `Qg` otherwise just divided equally among the online generators. Of course, the option would default to proportional scaling in order to maintain the current default behaviour.

Either way, `pfsoln` might benefit from some additional documentation. Particularly around handling infinite limits and zero `Qg` range.

**Comment by rdzman** [comment]
I agree about the documentation ... even if just to help me remember what I was doing. 😉 

The goal of this code was to make sure that (1) we never return an infeasible Q allocation if a feasible one exists and that (2) if there is no feasible allocation that the violations are proportional to the feasible range (when that is non-zero and finite) and something reasonable when it's not.

I've added some additional comments in 6f2ef7c. Let me know if there are specific things that are still unclear.

I'm not keen on the idea of including the option to simply split `Qg` equally since that could result in an infeasible assignment when a feasible one exists.
